apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploy-demo
   labels:
     app: nginx
spec:
   replicas: 3
   selector:
     matchLabels:
       app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
       containers:
       - name: cont-1
         image: nginx:1.14.2
         ports:
         - containerPort: 80
