apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploy-demo
   labels:
     app: nginx
spec:
   replicas: 3
   selector:
     matchLabels:
       app: nginx
   template:
     metadata:
       labels:
         app: nginx
     spec:
       containers:
       - name: cont-1
         image: nginx:1.14.2
         ports:
         - containerPort: 80


# kubectl apply -f deployment.yaml
# kubectl get deployment
# kubectl get rs
# kubectl get pod
# kubectl describe deployment <deployment name>


 Note: 
 **features of deployment:**
Automated Rollouts and Rollbacks
- Rollouts: Kubernetes can automatically deploy changes to your application or its configuration.
- Rollbacks: If something goes wrong, Kubernetes can revert to a previous version of the application.
