apiVersion: v1
kind: Pod
metadata:
 name: demo-pod

 spec:
    containers:
    - name: demo-pod
      image: nginx
      ports:
      - containerPort: 80


# kubectl apply -f pod.yaml
# kubectl get pod
# kubectl describe pod <pod-name>
# kubectl get pod -o wide
# kubect delete pod <pod-name>
