apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo
spec:
  replicas: 5
  selector:
    app: demo-app
  template:
    metadata:
      name: demo-app
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: nginx
